#!/usr/bin/env python3
"""Download 20 images generated by image_generate tool to local images/ dir."""
import urllib.request, os, json, sys

DATE = "20260810"

URLS = {
    "01": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020622cf00f4f4becb42a7_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=wzRtUfIRaWCapJ9JEZDNV40OeV4%3D&Expires=1786903590",
    "02": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020631a306fd22f2a54d93_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=XCw%2FHGZSWJ%2FaFMAFgsIXYq8nTQY%3D&Expires=1786903600",
    "03": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/202608100206410ce2c47dad764ead_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=zhdgYThCuf%2B2YaPYQwxRQkAUz20%3D&Expires=1786903610",
    "04": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/202608100206516ef6ecc47a1c463e_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=7z4OENBmnFlTtKwewEitwsi0ryk%3D&Expires=1786903622",
    "05": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/202608100207039a82ad0110494913_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=zndCLioZw8KOnWgUiplPQQS5ALg%3D&Expires=1786903632",
    "06": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020713e514c79403b84462_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=TjiEKghAiwNJXyCaxBlWwevFhWk%3D&Expires=1786903641",
    "07": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/2026081002072223056ae34ddb4aff_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=XHZXs5LeAR0aIk4HfvSLTPyZ1oY%3D&Expires=1786903653",
    "08": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/202608100207503436f05b87ae4add_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=zie0P5wHqsyzY8NfpNa%2BaeskP68%3D&Expires=1786903678",
    "09": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020759a4c24604457a4ca9_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=LsEsj2gA0h5Mf0iO9wK3SI01aIQ%3D&Expires=1786903690",
    "10": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/2026081002081159f22e8d2e244fbd_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=QP2fb0ZkzHVinYrfnUbdBWnqpUg%3D&Expires=1786903701",
    "11": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020823e67e54d5e12a4d93_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=02qT23BmjxUCKw496pa%2BJJkEzqI%3D&Expires=1786903711",
    "12": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020832360bcd91383946de_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=DKr1DlQH17D4vwRntJWkj0V%2FsaE%3D&Expires=1786903722",
    "13": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020844668578fcc30543eb_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=JGetOyGsv2Q90W8oQLyAaU6cZ%2FI%3D&Expires=1786903732",
    "14": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/202608100208539f2334a16ced447d_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=1mBgGQzYIlv0SKGdkz3mO96yPDc%3D&Expires=1786903741",
    "15": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020911da184e96adf845fd_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=4mCJqlc56tIXmym%2B4%2F9OoBIPYKw%3D&Expires=1786903763",
    "16": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020924e6b01caa662441aa_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=CH9AFDB72GIbkkui4kdA7yTyhd8%3D&Expires=1786903772",
    "17": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020933bc61180cf3fa433b_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=g2u93Su9%2FiHkArTj%2FnD4cmc1CKE%3D&Expires=1786903781",
    "18": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810020943ab9e0c5b7d624506_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=mukIcqMFb9McdCm3pxTgioYdyjI%3D&Expires=1786903792",
    "19": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/2026081002095335beb53fb7364efd_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=Cun4p6HgIJJcUZp8BU5%2FN8MElj8%3D&Expires=1786903801",
    "20": "https://maas-watermark-prod-new.cn-wlcb.ufileos.com/20260810021002c0e79dd5efef42ef_watermark.png?UCloudPublicKey=TOKEN_6df395df-5d8c-4f69-90f8-a4fe46088958&Signature=492My8KnjU7Vv1kTXoYtIlUgo0M%3D&Expires=1786903811",
}

os.makedirs("images", exist_ok=True)
results = {}
for num, url in URLS.items():
    out = f"images/news_{DATE}_{num}.png"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=60) as r:
            data = r.read()
        with open(out, "wb") as f:
            f.write(data)
        size = len(data)
        results[num] = size
        ok = "✓" if size > 10000 else "✗"
        print(f"[{ok}] {num}: {size} bytes  {out}")
    except Exception as e:
        results[num] = -1
        print(f"[ERR] {num}: {e}")

# Summary
ok_count = sum(1 for s in results.values() if s > 10000)
print(f"\nSummary: {ok_count}/20 images > 10KB")
